const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const FileManagerPlugin = require("filemanager-webpack-plugin");
const { VanillaExtractPlugin } = require("@vanilla-extract/webpack-plugin");
const { WebpackManifestPlugin } = require("webpack-manifest-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const webpack = require("webpack");
const HookShellScriptPlugin = require("hook-shell-script-webpack-plugin");

const exportsInit = (conf) => {
  return {
    watch: conf.watch,
    devtool: conf.devtool,
    entry: [path.resolve("src", "index.ts"), path.resolve("src", "styles.css")],
    output: {
      path: path.resolve("assets"),
      filename: `js/${conf.filename}.js`,
    },
    resolve: {
      alias: {
        normalize: path.resolve(
          __dirname,
          "./node_modules/normalize-css/normalize.css"
        ),
      },
    },
    module: {
      rules: [
        {
          test: /\.(ts|tsx)$/,
          exclude: /node_modules/,
          use: [
            {
              loader: "babel-loader",
              options: {
                babelrc: false,
                presets: [
                  "@babel/preset-typescript",
                  ["@babel/preset-react", { runtime: "automatic" }],
                  [
                    "@babel/preset-env",
                    { targets: { node: 14 }, modules: false },
                  ],
                ],
                plugins: ["@vanilla-extract/babel-plugin"],
              },
            },
          ],
        },
        {
          test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: require.resolve("css-loader"),
              options: {
                url: false, // Required as image imports should be handled via JS/TS import statements
              },
            },
          ],
        },
        {
          test: /\.(css)$/,
          exclude: /node_modules/,
          use: [MiniCssExtractPlugin.loader, "css-loader", "postcss-loader"],
        },
        // {
        //   test: /\.(png|jpg|gif|svg)$/,
        //   loader: 'file-loader',
        //   options: {
        //     outputPath: 'assets/'
        //   }
        // }
      ],
    },
    plugins: [
      // // Delete old files (prod files are deleted with dev files to avoid confusion)
      new FileManagerPlugin({
        events: {
          onStart: [
            {
              delete: [
                {
                  source: path.resolve("site", "assets", "js", "*"),
                },
                {
                  source: path.resolve("assets", "css", "*"),
                },
                {
                  source: path.resolve("assets", "js", "*"),
                },
                {
                  source: path.resolve("_data", "manifest.json"),
                },
              ],
            },
          ],
        },
      }),
      // // Create manifest with generated file names
      new WebpackManifestPlugin({
        fileName: "../../_data/manifest.json",
        writeToFileEmit: true,
        basePath: "",
        map: (f) => {
          f.path = f.path.replace(/^auto\//, "");
          return f;
        },
      }),
      new MiniCssExtractPlugin({
        filename: `css/${conf.filename}.css`,
      }),
      new VanillaExtractPlugin({}),
      conf.runAfterFirstCompilation,
    ],
    optimization: {
      minimizer: [new CssMinimizerPlugin({})],
      minimize: true,
    },
    watchOptions: {
      ignored: ["node_modules"],
    },
  };
};

// Dynamic value for dev and production environments
const setEnvConfig = (mode, hook) => {
  console.log("");
  console.log("mode: ", mode);
  console.log("hook: ", hook);
  console.log("");

  //webpack.js.org/api/compiler-hooks/#aftercompile
  https: var runAfterFirstCompilation;

  switch (mode) {
    case "development":
      console.log(
        `\n=====> DEV CONFIG${hook ? ` with hook: "${hook}"` : ""}\n`
      );
      if (hook === "cuttlebelle") {
        runAfterFirstCompilation = new HookShellScriptPlugin({
          afterPlugins: ["cuttlebelle -w"],
        });
      }
      return {
        watch: true,
        filename: "[name]",
        devtool: "source-map",
        runAfterFirstCompilation,
      };
    default:
      console.log("\n=====> PROD CONFIG\n");
      return {
        watch: false,
        filename: "[name].[fullhash]",
        devtool: "inline-source-map",
        runAfterFirstCompilation,
      };
  }
};

module.exports = (env, args) => {
  return exportsInit(setEnvConfig(args.mode, env.hook || false));
};
